'use strict' 
require('./chars.html') 
require('./clients.html') 
require('./contact.html') 
require('./morro.html') 
require('./noen.html') 
require('./products.html') 
require('./pronouns.html') 
require('./root.html') 
require('./services.html') 
require('./synth.html') 
require('./test.html') 
require('./tones.html') 
require('./unshader.html') 
require('./unt.html') 
require('./verbs.html') 
require('./wubi.html') 
